// src/env.ts
// The global `interface Env` (from worker-configuration.d.ts, generated by
// `wrangler types`) already contains: all DO bindings, LILIUM_DB, vars,
// CF_VERSION_METADATA. Augment it with secret fields (set via `wrangler secret put`,
// never written to wrangler.jsonc so not in the generated types).
declare global {
  interface Env {
    JWT_SECRET: string;
    S3_ACCESS_KEY_ID: string;
    S3_SECRET_ACCESS_KEY: string;
    SENTRY_DSN: string;
    /** Set to "1" only in wrangler.test.jsonc; absent in production. */
    ALLOW_INTERNAL_TEST_ROUTES?: string;
    /** Read-only SQL debug endpoint token (set via `wrangler secret put DEBUG_TOKEN`). */
    DEBUG_TOKEN?: string;
    CHAT_ARCHIVE_QUEUE: Queue<import("./archive/payload").ArchiveRecord>;
  }
}

// Re-export as a local type alias so other modules can `import type { Env } from "../env"`
// uniformly. The alias resolves to the augmented global Env declared above + in
// worker-configuration.d.ts.
export type Env = globalThis.Env;
